#!/usr/bin/env bash

# Usage:
# e2e/scripts/in-docker some-fancy-command --with-args

docker run \
    --platform linux/amd64 \
    -v $(pwd):/atlascode \
    --user atlascode \
    $([ -z "$CI" ] && echo "-it" || echo "") \
    atlascode-e2e $@
